# Generated by Django 3.2.16 on 2022-10-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_periodictasktenantlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='addresse',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='client',
            name='email_of_account_HRmanager',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email_of_account_manager',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lincence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='name_of_account_HRmanager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name_of_account_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='poc',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='client',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tel_of_account_HRmanager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tel_of_account_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
